# Generated by Django 2.2.13 on 2021-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.TimeField(),
        ),
    ]
