# Generated by Django 2.2.13 on 2021-05-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210510_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
