# Generated by Django 2.2.13 on 2021-05-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_comment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('comment_section', models.TextField()),
            ],
        ),
    ]
